version: '3.8'

services:
  db:
    image: postgres:16.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi_challenge
    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql_data:
