version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./src:/app
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - db

  db:
    image: postgis/postgis:16-3.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi_challenge
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

volumes:
  postgresql_data:
